### ISSUE TITLE
'Getting Started by Forge by Wilson' url isn't correct

### ISSUE THREAD

**Issue by Reimao** [crisgarner/awesome-foundry#2]
Current url: https://w.mirror.xyz/mOUlpgkWA178HNUW7xR20TdbGRV6dMid7uChqxf9

Correct url: https://w.mirror.xyz/mOUlpgkWA178HNUW7xR20TdbGRV6dMid7uChqxf9Z58

**Comment by crisgarner** [comment]
Thanks! Fixing it now
