### ISSUE TITLE
Hardhat template with Foundry

### ISSUE THREAD

**Issue by pcaversaccio** [crisgarner/awesome-foundry#8]
I've created a fully-fledged Hardhat project template based on TypeScript [here](https://github.com/pcaversaccio/hardhat-project-template-ts) that also integrates Foundry & Foundry CI actions. Feel free to add it to your resources.

**Comment by pcaversaccio** [comment]
@crisgarner are you interested - if not I can close this issue.

**Comment by crisgarner** [comment]
hey, @pcaversaccio if can you make a PR? I can add it then
